version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fishbase-postgres
    environment:
      POSTGRES_DB: fishbase
      POSTGRES_USER: fishuser
      POSTGRES_PASSWORD: fishpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fishuser -d fishbase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: